# ============================================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: app
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: app-sa
      containers:
        - name: product-service
          image: us-east1-docker.pkg.dev/white-watch-464115-t0/dev-microservices-repo/product-service:v1
          ports:
            - containerPort: 8082
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: product-service-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
          args:
            - "--structured-logs"
            - "--port=3306"
            - "--private-ip"
            - "white-watch-464115-t0:us-east1:dev-mysql"   #CLOUD_SQL_CONNECTION_NAME
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: app
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP