apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: app
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: app-sa
      containers:
        # Application Container
        - name: user-service
          image: us-east1-docker.pkg.dev/white-watch-464115-t0/dev-microservices-repo/user-service:v1

          ports:
            - containerPort: 8081

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 18    # Allows up to 180 seconds for startup

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

        # Cloud SQL Proxy Sidecar
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
          args:
            - "--structured-logs"
            - "--port=3306"
            - "--private-ip"
            - "white-watch-464115-t0:us-east1:dev-mysql"

          securityContext:
            runAsNonRoot: true

          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "30m"
              memory: "64Mi"